"""Initial schema

Revision ID: c772a2bb3817
Revises: 
Create Date: 2026-06-13 00:25:07.279738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# SQLite only auto-increments INTEGER PRIMARY KEY, not BIGINT PRIMARY KEY.
_BigIntPK = sa.BigInteger().with_variant(sa.Integer(), "sqlite")


# revision identifiers, used by Alembic.
revision: str = 'c772a2bb3817'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('external_product_id', sa.String(length=128), nullable=True),
    sa.Column('marketplace', sa.String(length=64), nullable=True),
    sa.Column('title_current', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('crawl_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_tenant_status', 'products', ['tenant_id', 'status'], unique=False)
    op.create_table('scrape_tasks',
    sa.Column('id', _BigIntPK, autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('file_paths', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('ix_scrape_tasks_status', 'scrape_tasks', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', _BigIntPK, autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('review_id', sa.String(length=128), nullable=False),
    sa.Column('user_nick', sa.String(length=255), nullable=True),
    sa.Column('review_date', sa.String(length=32), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('append_content', sa.Text(), nullable=True),
    sa.Column('append_date', sa.String(length=32), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('picture_urls', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_product', 'reviews', ['product_id'], unique=False)
    op.create_index('ix_reviews_review_id', 'reviews', ['review_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', _BigIntPK, autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('crawl_status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('list_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('availability_status', sa.String(length=32), nullable=True),
    sa.Column('seller_name', sa.String(length=255), nullable=True),
    sa.Column('page_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_product_captured', 'snapshots', ['product_id', 'captured_at'], unique=False)
    op.create_table('changes',
    sa.Column('id', _BigIntPK, autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('baseline_snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('current_snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('change_date', sa.Date(), nullable=False),
    sa.Column('has_change', sa.Boolean(), nullable=False),
    sa.Column('change_types', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('diff_payload', sa.Text(), nullable=True),
    sa.Column('ai_summary_title', sa.String(length=255), nullable=True),
    sa.Column('ai_summary_text', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('notification_status', sa.String(length=32), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_snapshot_id'], ['snapshots.id'], ),
    sa.ForeignKeyConstraint(['current_snapshot_id'], ['snapshots.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_changes_notification', 'changes', ['tenant_id', 'notification_status', 'created_at'], unique=False)
    op.create_index('ix_changes_product_date', 'changes', ['product_id', 'change_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_changes_product_date', table_name='changes')
    op.drop_index('ix_changes_notification', table_name='changes')
    op.drop_table('changes')
    op.drop_index('ix_snapshots_product_captured', table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index('ix_reviews_review_id', table_name='reviews')
    op.drop_index('ix_reviews_product', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_scrape_tasks_status', table_name='scrape_tasks')
    op.drop_table('scrape_tasks')
    op.drop_index('ix_products_tenant_status', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
